"""Verdict + secrets_found + Pass 2 execution results.

The ``verdict_label`` is a categorical token. The continuous 0-100
maliciousness_score is computed from the logprob distribution over that
token by the statistical engine — NOT generated by the model.
See shared/utils/scoring.py.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from shared.types.enums import (
    ConfidenceLabel,
    CveFeedSourceType,
    DetectionSource,
    HypothesisResult,
    RecommendedAction,
    SandboxType,
    ValidationStatus,
    VerdictLabel,
)


class SecretFound(BaseModel):
    """Triage record for secret detection. NEVER store the raw secret value."""

    model_config = ConfigDict(extra="forbid")

    secret_type: str
    line_number: int
    detection_source: DetectionSource
    confidence: ConfidenceLabel
    llm_judgment: str  # confirmed | rejected
    llm_reasoning: str = Field(max_length=300)
    context_flags: list[str] = Field(default_factory=list)


class Verdict(BaseModel):
    model_config = ConfigDict(extra="forbid")

    verdict_label: VerdictLabel = Field(
        description=(
            "Categorical classification. The system computes the 0-100 maliciousness "
            "score from the logprob distribution over this token."
        ),
    )
    # Bound matches dast.orchestrator._LOG_SUMMARY_MAX (truncated on
    # ingest). Generous enough that a concise verdict summary is never
    # rejected; the request schema has no hard cap (see dast/prompts.py).
    log_summary: str = Field(max_length=400)
    recommended_action: RecommendedAction | None = None
    validation_status: ValidationStatus | None = Field(
        default=None,
        description="Set by orchestrator after Pass 2.",
    )


# ── Execution results (Pass 2 only) ────────────────────────────────────────────
class ValidatedHypothesis(BaseModel):
    model_config = ConfigDict(extra="forbid")

    hypothesis_id: str
    finding_ref: str
    result: HypothesisResult
    iterations: int = Field(ge=0)
    poc_output: str | None = Field(default=None, max_length=1000)
    confidence_override: float | None = Field(default=None, ge=0, le=1)
    poc_summary: str | None = Field(default=None, max_length=400)


class EmergentFinding(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str = Field(pattern=r"^EF[0-9]{3}$")
    type: str
    severity: str
    title: str = Field(max_length=120)
    explanation: str = Field(max_length=500)
    poc_output: str = Field(max_length=500)


class Pass2Budget(BaseModel):
    """v3.1: Budget tracking to prevent Pass 2 queue flooding on large repos."""

    model_config = ConfigDict(extra="forbid")

    max_files_per_scan: int | None = None
    max_total_sandbox_time_sec: int | None = None
    budget_exhausted: bool = False
    files_skipped: int = 0
    prioritization_method: str | None = Field(
        default=None,
        description="E.g., 'priority_score * (1 - model_uncertainty)'.",
    )


class CveFeedSource(BaseModel):
    """v3.1: Provenance of CVE context. Critical for air-gapped deployments."""

    model_config = ConfigDict(extra="forbid")

    source_type: CveFeedSourceType
    bundle_id: str | None = None
    bundle_date: str | None = None  # ISO date
    cve_coverage_gap_days: int | None = None


class ExecutionResults(BaseModel):
    """Populated ONLY by Pass 2. Null when Pass 2 did not run."""

    model_config = ConfigDict(extra="forbid")

    pass2_executed: bool
    orchestrator_model: str | None = None
    code_agent_model: str | None = None
    sandbox_type: SandboxType | None = None
    validated_hypotheses: list[ValidatedHypothesis] = Field(default_factory=list)
    emergent_findings: list[EmergentFinding] = Field(default_factory=list)
    total_sandbox_time_sec: float | None = None
    total_iterations: int | None = None
    pass2_budget: Pass2Budget | None = None
    cve_feed_source: CveFeedSource | None = None
